import { SiteFooter, SiteNav } from '../components/SiteNav';

const values=[
  ['Scientific Integrity','Credible, balanced and evidence-based scientific content.','Evidence'],
  ['Ethics & Transparency','Responsible and transparent engagement across programmes, partnerships and sponsorships.','Trust'],
  ['Relevance','Scientific programmes aligned with emerging evidence, unmet needs and regional healthcare priorities.','Region'],
  ['Collaboration','Bringing together diverse healthcare stakeholders to enable meaningful scientific exchange.','Connect'],
  ['Scientific Independence','Protecting scientific credibility through appropriate governance and separation of scientific and commercial interests.','Independent'],
  ['Quality & Impact','High standards in programme design and delivery, focused on practical value and real-world impact.','Impact']
];

const valueActions=[
  ['Scientific Integrity','Evidence-based programme development, credible faculty selection, scientific review and balanced content.'],
  ['Ethics & Transparency','Clear sponsorship principles, transparent roles, appropriate disclosures and responsible engagement.'],
  ['Relevance','Topics shaped by current evidence, emerging science, unmet needs and regional healthcare priorities.'],
  ['Collaboration','Engagement across clinicians, researchers, institutions, policymakers, regulators and industry stakeholders.'],
  ['Scientific Independence','Advisory input, defined scientific governance and appropriate separation of scientific and commercial interests.'],
  ['Quality & Impact','Structured planning, strong delivery standards, participant feedback and practical, real-world takeaways.']
];

export default function AboutPage(){return <div className="pageShell"><SiteNav/><section className="pageHero"><p className="pageEyebrow">About Seroevents</p><h1>Scientific platforms built for evidence, exchange and real-world impact.</h1><p>Seroevents is a specialized scientific events and healthcare engagement company based in the UAE, focused on medical conferences, scientific forums, expert meetings and professional healthcare education.</p></section>

<section className="contentSection"><div className="contentGrid"><div className="contentCard"><h2>Who We Are</h2><p>We develop and deliver medical and scientific events designed around evidence, professional exchange and meaningful collaboration. Our work brings together local, regional and international expertise through carefully developed conferences, forums, meetings and educational programmes.</p></div><div className="contentCard"><h2>Our Aim</h2><p>To enable meaningful scientific dialogue that helps stakeholders evaluate emerging evidence, understand its regional relevance and translate it into informed decisions and real-world impact.</p></div></div></section>

<section className="contentSection white"><p className="pageEyebrow">Vision · Mission · Aim</p><div className="strategyFlow"><article className="strategyCard featured"><span className="strategyNumber">01</span><p className="strategyKicker">Vision</p><h2>Trusted benchmark for scientific programmes.</h2><p>To be a trusted benchmark for robust, research-driven and evidence-based scientific programmes that advance healthcare and scientific engagement across the region.</p></article><div className="strategyConnector" aria-hidden="true"><span>→</span></div><article className="strategyCard"><span className="strategyNumber">02</span><p className="strategyKicker">Mission</p><h2>Connect evidence, expertise and the region.</h2><p>To create credible scientific platforms that connect evidence, expertise and regional perspectives to advance healthcare.</p></article><div className="strategyConnector" aria-hidden="true"><span>→</span></div><article className="strategyCard"><span className="strategyNumber">03</span><p className="strategyKicker">Aim</p><h2>Turn dialogue into impact.</h2><p>To enable meaningful scientific dialogue that helps stakeholders evaluate emerging evidence, understand its regional relevance and translate it into informed decisions and real-world impact.</p></article></div></section>

<section className="contentSection"><p className="pageEyebrow">Our Values</p><h2 className="valuesHeadline">The standards behind every Seroevents scientific platform.</h2><div className="valuesDynamicGrid">{values.map(([title,text,tag],index)=><article className="valueDynamicCard" key={title}><div className="valueCardTop"><span className="valueIndex">0{index+1}</span><span className="valueTag">{tag}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>

<section className="contentSection valuesInAction"><div className="valuesActionIntro"><p className="pageEyebrow">Values in Action</p><h2>How we put our values into practice.</h2><p>Our values are embedded in our governance, scientific review, stakeholder engagement, partnership model and programme delivery.</p></div><div className="actionPath">{valueActions.map(([title,text],index)=><article className="actionStep" key={title}><span>{String(index+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>

<section className="contentSection white"><p className="pageEyebrow">The Origin of Sero</p><div className="contentGrid"><div className="contentCard dark"><h2>Why the name Sero?</h2><p><strong>The name “Sero” comes from serotonin.</strong> Serotonin is a signalling molecule closely associated with communication within the human body and with aspects of mood, wellbeing and human experience.</p></div><div className="contentCard"><h2>From Serotonin to Seroevents</h2><p>We chose Sero because it connects our identity directly to science while also representing connection between people.</p><p>That idea reflects what Seroevents is built to do: bring together healthcare professionals, scientific experts, institutions and partners around evidence, dialogue and meaningful engagement.</p><p>The molecular structure in our visual identity reinforces the origin of the name and our connection to healthcare and science.</p></div></div></section>

<section className="contentSection"><div className="emptyState"><p className="pageEyebrow">Leadership</p><h2>Meet our Managing Director</h2><p>Mr. Abdel Karim Ajam serves as Managing Director of Seroevents.</p><div className="linkRow"><a className="pillLink orange" href="/seroevents-website/about/managing-director/">View Managing Director Profile</a></div></div></section>

<section className="contentSection white"><p className="pageEyebrow">Scientific Governance</p><div className="contentGrid"><div className="contentCard dark"><h2>Scientific Advisory Board</h2><p>Seroevents is supported by a Scientific Advisory Board that provides independent scientific guidance across selected programmes and initiatives.</p></div><div className="contentCard"><h2>Supporting Scientific Quality</h2><p>The Board supports the development of relevant, credible and professionally structured scientific content, helping ensure that programmes remain aligned with current clinical priorities, educational objectives and stakeholder needs.</p><p>Its role is advisory, with a focus on scientific quality, programme relevance, faculty input and professional standards.</p></div></div></section>

<section className="contentSection white"><p className="pageEyebrow">Our Approach</p><div className="contentGrid"><div className="contentCard"><h3>Science First</h3><p>Every strong scientific event starts with a clear purpose. Scientific relevance stays at the centre of programme development.</p></div><div className="contentCard"><h3>The Right Experts</h3><p>We support the identification and coordination of respected local, regional and international speakers who can contribute meaningful expertise.</p></div><div className="contentCard"><h3>The Right Stakeholders</h3><p>Focused participation by clinicians, researchers, institutions, policymakers, regulators and industry can create greater impact than scale alone.</p></div><div className="contentCard"><h3>Professional Delivery</h3><p>Strong operational management transforms a scientific concept into a professionally delivered meeting.</p></div></div></section><SiteFooter/></div>}
