import { events } from '../lib/events';
import { NavigationMenu } from './components/SiteNav';

const services = [
  ['Medical Conferences', 'Development and management of professional medical conferences across specialties.'],
  ['Scientific Forums', 'Focused meetings designed around a specialty, clinical topic or area of healthcare development.'],
  ['Expert Meetings & Roundtables', 'Selected expert groups for structured scientific and professional discussion.'],
  ['Medical Education Programmes', 'Educational activities for healthcare professionals, from scientific updates to specialist workshops.'],
  ['Scientific Programme Development', 'Programme architecture, session planning, topic development, faculty planning and agenda management.'],
  ['End-to-End Event Management', 'Venue, production, registration, logistics, delegate communications and on-site operations.'],
];

const audiences = ['Healthcare Professionals','Scientific Committees','Medical Societies','Hospitals & Healthcare Groups','Universities & Academic Institutions','Research Organisations','Pharmaceutical & Biotechnology Companies','Medical Device & Diagnostic Companies','Healthcare Technology Organisations'];

function BrandMark() {
  return <div className="brandMark" aria-label="Seroevents"><span className="brandSymbol" aria-hidden="true"><i className="node n1" /><i className="node n2" /><i className="node n3" /><i className="node n4" /><i className="node n5" /><i className="bond b1" /><i className="bond b2" /><i className="bond b3" /><i className="bond b4" /></span><span className="brandText">Seroevents</span></div>;
}

export default function Home() {
  return <main>
    <header className="siteHeader"><div className="homeNavLeft"><NavigationMenu /><a className="brandLink" href="/seroevents-website/"><BrandMark /></a></div><nav className="nav" aria-label="Main navigation"><a href="/seroevents-website/about/">About</a><a href="/seroevents-website/services/">Services</a><a href="/seroevents-website/scientific-areas/">Scientific Areas</a><a href="/seroevents-website/partners/">Partnerships</a><a href="/seroevents-website/events/">Events</a></nav><a className="headerCta" href="/seroevents-website/partners/">Partner With Us</a></header>

    <section className="hero" id="top"><div className="heroGlow glowOne" /><div className="heroGlow glowTwo" /><div className="moleculeGrid" aria-hidden="true" /><div className="heroContent"><p className="eyebrow">Scientific Events & Healthcare Engagement · UAE</p><h1>Where Scientific Expertise Meets Meaningful Engagement</h1><p className="heroLead">Scientific conferences, healthcare forums, expert meetings, and professional medical education — developed and delivered in the UAE.</p><div className="heroActions"><a className="button buttonPrimary" href="/seroevents-website/events/">Upcoming Events</a><a className="button buttonGhost" href="/seroevents-website/events/past/">Past Events</a></div></div><div className="heroPanel"><div className="heroPanelTop"><span>Scientific engagement, professionally delivered</span><span className="statusDot">●</span></div><div className="heroPanelBody"><div><strong>Robust Science</strong><span>Evidence-based and current</span></div><div><strong>Credible Experts</strong><span>Relevant specialist voices</span></div><div><strong>Practical Value</strong><span>Clear takeaways for healthcare practice</span></div></div></div></section>

    <section className="section upcomingHomeSection" id="upcoming-event"><div className="sectionHeadingRow"><div><div className="sectionLabel light">01 · Upcoming Event</div><h2>What’s next at Seroevents.</h2></div><p className="lightText">A focused UAE leadership and scientific programme exploring the future of healthcare revenue cycle.</p></div><div className="upcomingHomeFeature"><article className="eventCard upcomingCard"><div className="eventTopline"><span>Upcoming · 7–8 May 2027</span><span>Abu Dhabi</span></div><img className="upcomingArtwork" src="/seroevents-website/RCM%20Flayer.png" alt="Abu Dhabi Healthcare Revenue Cycle Summit 2027"/><div className="upcomingBody"><h3>Abu Dhabi Healthcare Revenue Cycle Summit 2027</h3><p><strong>Shaping the Future of Healthcare Revenue Cycle in the UAE</strong></p><p>Reimbursement Transformation · Case-Mix Integrity · Payment Integrity · Clinical Costing · Data & AI</p><p>7–8 May 2027 · Abu Dhabi, UAE</p><a className="textLink" href="/seroevents-website/events/abu-dhabi-healthcare-revenue-cycle-summit-2027/">Explore the Summit →</a></div></article></div></section>

    <section className="section pastHomeSection" id="past-events"><div className="sectionHeadingRow"><div><div className="sectionLabel">02 · Past Events</div><h2>Scientific programmes we have delivered.</h2></div><p>Selected completed events, presented as a record of scientific content, faculty engagement and professional delivery.</p></div><div className="eventGrid pastEventGrid">{events.map(event=><article className={`eventCard ${event.accent}`} key={event.title}><div className="eventTopline"><span>Past Event · {event.year}</span><span>Completed</span></div><div className="eventArtwork" aria-hidden="true"><span className="eventRing ringOne"/><span className="eventRing ringTwo"/><span className="eventRing ringThree"/></div><div className="eventContent"><h3>{event.title}</h3><p>{event.description}</p><div className="eventMeta"><span>{event.date}</span><span>{event.location}</span></div><a className="textLink" href={`/seroevents-website/events/${event.slug}/`}>View case study →</a></div></article>)}</div><div className="pastEventsAction"><a className="button pastEventsButton" href="/seroevents-website/events/past/">View All Past Events</a></div></section>

    <section className="section servicesSection"><div className="sectionHeadingRow"><div><div className="sectionLabel">03 · Vision · Mission · Aim</div><h2>Built around scientific credibility and practical value.</h2></div></div><div className="serviceGrid compactGrid"><article className="serviceCard"><span className="serviceNumber">01</span><h3>Vision</h3><p>To become a trusted benchmark for high-quality scientific events in the UAE and the region, recognised for robust, evidence-based and up-to-date programmes that translate knowledge into meaningful clinical practice.</p></article><article className="serviceCard"><span className="serviceNumber">02</span><h3>Mission</h3><p>To develop scientifically rigorous healthcare programmes that bring together credible experts, current evidence and relevant professional audiences for meaningful education, exchange and collaboration.</p></article><article className="serviceCard"><span className="serviceNumber">03</span><h3>Our Aim</h3><p>To deliver practical value through relevant scientific content, evidence-based discussion and clear takeaways that can inform everyday clinical practice.</p></article></div><div className="pillRow"><span>Robust Science</span><span>Current Evidence</span><span>Practical Takeaways</span></div></section>

    <section className="section whySection"><div className="sectionLabel">04 · Why Seroevents</div><div className="sectionHeadingRow"><div><h2>Scientific standards. Professional execution.</h2></div><p>Medical events require both scientific credibility and disciplined delivery.</p></div><div className="whyGrid compactWhy"><div className="whyItem"><span>01</span><h3>Scientific Integrity</h3><p>Credible, balanced and evidence-based content.</p></div><div className="whyItem"><span>02</span><h3>Relevance</h3><p>Current evidence and topics aligned with healthcare priorities.</p></div><div className="whyItem"><span>03</span><h3>Focused Engagement</h3><p>Credible experts and carefully selected professional audiences.</p></div><div className="whyItem"><span>04</span><h3>Professional Delivery</h3><p>Structured coordination, production and delegate experience.</p></div></div></section>

    <section className="section servicesSection" id="services"><div className="sectionHeadingRow"><div><div className="sectionLabel">05 · Our Services</div><h2>From scientific concept to professional delivery.</h2></div></div><div className="serviceGrid compactGrid">{services.map((service,index)=><article className="serviceCard" key={service[0]}><span className="serviceNumber">0{index+1}</span><h3>{service[0]}</h3><p>{service[1]}</p></article>)}</div></section>

    <section className="section servicesSection"><div className="sectionHeadingRow"><div><div className="sectionLabel">06 · Who We Work With</div><h2>Across the healthcare ecosystem.</h2></div></div><div className="pillRow">{audiences.map(item=><span key={item}>{item}</span>)}</div></section>

    <section className="contactSection" id="contact"><div><div className="sectionLabel light">07 · Partnership</div><h2>Focus on the science. We support the event around it.</h2><p>Work with Seroevents to develop and deliver credible, relevant and professionally structured medical meetings.</p></div><div className="contactActions"><a className="button buttonPrimary" href="/seroevents-website/partners/">Discuss a Partnership</a><a className="button buttonGhost" href="/seroevents-website/contact/">Contact Us</a></div></section>
    <footer><BrandMark /><p>Scientific Events & Healthcare Engagement</p><p>© {new Date().getFullYear()} Seroevents. All rights reserved.</p></footer>
  </main>;
}
