import { SiteFooter, SiteNav } from '../components/SiteNav';

const opportunities=['Development of new medical conferences','Management of existing scientific meetings','Scientific forums','Educational programmes','Expert meetings','Institutional collaborations','Professional healthcare events','Industry-supported scientific initiatives'];

const supporters=[
  {name:'Amgen',role:'Gold Supporter',event:'Innovative Therapy Implementation (ITI) Summit 2024'},
  {name:'Sobi',role:'Silver Supporter',event:'Innovative Therapy Implementation (ITI) Summit 2024'},
  {name:'Leader Life Sciences',role:'Sponsor',event:'FCHS Future Medicine Symposium 2024'},
  {name:'Abu Dhabi Stem Cells Center (ADSCC)',role:'Sponsor',event:'FCHS Future Medicine Symposium 2024'},
  {name:'ACTVET',role:'Sponsor',event:'FCHS Future Medicine Symposium 2024'},
];

export default function PartnersPage(){return <div className="pageShell"><SiteNav/><section className="pageHero"><p className="pageEyebrow">Partnerships</p><h1>Partner With Seroevents.</h1><p>Seroevents welcomes collaboration with scientific leaders, healthcare institutions, medical societies and organisations seeking to create meaningful healthcare and scientific programmes.</p></section><section className="contentSection"><div className="contentGrid"><div className="contentCard"><h2>From idea to delivery</h2><p>Whether developing a new scientific platform or supporting an established meeting, our role is to provide the structure, coordination and professional execution required to turn an idea into a successful event.</p></div><div className="contentCard dark"><h2>Partnership opportunities</h2><div className="pillRow">{opportunities.map(item=><span key={item}>{item}</span>)}</div></div></div></section><section className="contentSection white"><p className="pageEyebrow">Selected Partners & Supporters</p><h2 style={{maxWidth:'820px'}}>Organisations that have supported or collaborated on selected Seroevents programmes.</h2><p style={{maxWidth:'820px',color:'#667085',lineHeight:1.7}}>The organisations below are presented according to their documented role in specific events. Inclusion does not imply an ongoing corporate partnership or endorsement.</p><div className="contentGrid" style={{marginTop:'32px'}}>{supporters.map(item=><div className="contentCard" key={item.name}><p className="pageEyebrow" style={{marginBottom:'12px'}}>{item.role}</p><h3>{item.name}</h3><p>{item.event}</p></div>)}</div></section><section className="contentSection white"><p className="pageEyebrow">For Conference Chairs & Scientific Leaders</p><div className="contentGrid"><div className="contentCard"><h2>Focus on the Science. We Support the Event Around It.</h2><p>Seroevents works with conference chairs and scientific leaders to provide the professional infrastructure required to develop and deliver high-quality medical meetings.</p></div><div className="contentCard"><h3>How we can support</h3><p>Programme coordination, speaker management, partnership support, venue and supplier management, delegate experience, event production and operational delivery — allowing scientific leaders to concentrate on the quality and direction of the programme.</p></div></div><div className="linkRow"><a className="pillLink orange" href="/seroevents-website/contact/">Discuss a Partnership</a></div></section><SiteFooter/></div>}
